# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 00:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Your name')),
                ('email', models.EmailField(max_length=250, verbose_name='Your email address')),
                ('subject', models.CharField(max_length=120, verbose_name='Message Subject')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(750)], verbose_name='Your message')),
                ('referrer', models.CharField(blank=True, max_length=254, verbose_name='referrer')),
            ],
        ),
    ]
