# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='identifier',
            field=models.CharField(blank=True, max_length=15, verbose_name='Identifier'),
        ),
    ]
