#!/bin/bash

# Ignoring autogenerated files
#  -- Migration directories
# Ignoring error codes
#  -- E125 continuation line with same indent as next logical line
#  -- E128 continuation line under-indented for visual indent
#  -- E225 missing whitespace around operator
#  -- E501 line too long

pep8 --exclude=migrations --ignore=E125,E128,E225,E501 .
